### ISSUE TITLE
Address Milestone 1 Feedback (2.2.2 Personas)

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4117-2023-2024-s2/semester-project-uprmarketplace#95]
Adress the following feedback for the milestone 1 documentation:
The personas are one-dimensional, they only present to person with respect to the project that you pursue. The problem with that is that the personas do not unfold their strength in this way. To unfold their strength, personas must have personality traits that make them memorable, that make them so familiar that you feel you have known the persona all your life.
Recommended Priority: 7
Recommended Difficulty: 4

**Comment by warm007** [comment]
Rodrigo Báez

Rodrigo Báez is an 18-year-old first-year student, who was just accepted into RUM a couple of months ago. He enrolled in the Mechanical Engineering program and will be taking a couple of classes with labs in his first semester, however, he had no idea that he had to purchase all his own lab equipment, such as the coat, glasses, gloves, and the manual! Coming from a background where community spirit and sustainability were valued, Rodrigo grew up in a small, tight-knit community that emphasized supporting local initiatives and environmental conservation. This upbringing instilled in him a strong sense of resourcefulness and a budget-conscious approach to life, traits that now guide him as he navigates the unexpected financial demands of college life. Surprised by the need to purchase his own laboratory equipment, a cost he had not anticipated, Rodrigo finds himself in a challenging situation, trying to balance his academic requirements with his personal savings goal: having an electric bicycle as a testament to his commitment to Ecological transport.

Rodrigo is characterized by his ecological awareness and social commitment. He is passionate about renewable energy and dreams of contributing to sustainable solutions in his future career. However, the immediate challenge of managing unexpected college expenses threatens to derail your e-bike savings plan. Balancing academic responsibilities, a part-time job, and personal interests in sustainability and community service, Rodrigo faces the typical challenges of a college freshman, along with the added stress of his own financial situation. He envisions a platform that not only helps students like him find and trade lab equipment at lower costs, but also serves as a hub for sharing resources, sustainable living tips, and academic support.

**Comment by warm007** [comment]
Sarah Muñiz
Sarah is a dedicated third-year Chemical Engineering student who has navigated the challenging waters of university life with ambition and a clear focus on her academic goals. Her personality is characterized by her pragmatic and efficient approach to challenges. She values solutions that save time and reduce stress, reflecting her methodical nature as a Chemical Engineering student. Her experiences have made her an advocate for efficiency and convenience, especially in a university environment where time is money. Beyond her academic and logistical challenges, Sarah is passionate about her field of study and constantly seeks ways to apply her knowledge in practical settings. Additionally, she participates in extracurricular activities related to Chemical Engineering, where she explores the real-world applications of her courses. Despite her busy schedule, she takes the time to interact with her community and share ideas and advice with younger students.
As she progresses through her demanding program, Sarah encounters a major challenge outside of her rigorous academic commitments: managing the constant cycle of buying and selling textbooks. This process has proven not only time-consuming but also inefficient, as she struggles to find platforms that offer the exposure necessary to sell her books quickly and at fair prices. Her experience with posting listings on multiple platforms and forums has been fraught with frustration, highlighting the need for a more streamlined solution.
Because she has a couple more years left in her college career, Sarah is well aware that the textbook cycle will continue. The ideal solution is a platform that simplifies this process, where she can effortlessly sell books she no longer needs and find the ones she needs just as easily. She envisions a service that could minimize hassles and maximize her efficiency, allowing her to focus more on her studies and less on managing her book inventory.

**Comment by warm007** [comment]
Carlos Sánchez
Carlos is a recent graduate from the University of Puerto Rico at Mayagüez (UPRM), with a degree that marks the culmination of years of hard work and dedication. Since his graduation two years ago, he has held on to his textbooks, not out of necessity, but because the prospect of selling them seemed daunting and inefficient. The methods available to sell or even give away his books seemed too cumbersome and time-consuming, so the effort didn't seem worth it. However, as the physical space around him becomes increasingly cluttered with unused textbooks, Carlos recognizes the need to declutter and make room for his new professional life and his interests.
In the years since his graduation, Carlos has made the transition to the professional world, where the skills and knowledge acquired during his time at RUM continue to be of great use to him. However, as he progresses, the physical remains of his academic past no longer have the same relevance, prompting him to act. Carlos's approach to this task is pragmatic and he is driven by a clear goal: to free up space efficiently. He values simplicity and ease of use on digital platforms, reflecting his broader preference for simple, practical solutions in life. Despite being willing to part with his books for minimal cost, or even free, Carlos insists on a process that respects his time and effort, ensuring that the books quickly reach someone who can benefit from them.
